---
- name: Restart mirror registry
  ansible.builtin.systemd:
    name: "container-{{ mirror_registry_container_name }}"
    state: restarted
    daemon_reload: true

- name: Update CA trust store
  ansible.builtin.command:
    cmd: update-ca-trust
  changed_when: true
